# version: '3.3'
# services:
#     openhab:
#         image: 'openhab/openhab:3.0.1'
#         container_name: openhab
#         # network_mode: host
#         ports:
#             - 8081:8081
#         volumes:
#             - '/etc/localtime:/etc/localtime:ro'
#             - '/etc/timezone:/etc/timezone:ro'
#             # - './openhab_addons:/openhab/addons'
#             # - './openhab_conf:/openhab/conf'
#             # - './openhab_userdata:/openhab/userdata'
#         environment:   
#             # - USER_ID=1001
#             # - GROUP_ID=9001
#             - OPENHAB_HTTP_PORT=8081
#             - OPENHAB_HTTPS_PORT=8444
#         restart: always
        
version: '2.2'

services:
  openhab:
    image: "openhab/openhab:3.0.1"
    container_name: "hab-server"
    restart: "unless-stopped"
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "./openhab_addons:/openhab/addons"
      - "./openhab_conf:/openhab/conf"
      - "./openhab_userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"