version: '2'

services:
  rabbitmq:
    container_name: 'rabbitmq'    
    image: docker.io/bitnami/rabbitmq:3.8
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
       - RABBITMQ_SECURE_PASSWORD=yes
       - RABBITMQ_USERNAME=user
       - RABBITMQ_PASSWORD=test
    volumes:
      - 'rabbitmq_data:/bitnami'
volumes:
  rabbitmq_data:
    driver: local
