version: '3'
services:
    neo4j:
        container_name: 'neo4j'
        ports:
            - '7474:7474'
            - '7687:7687'
        volumes:
            - './data:/data'
        image: neo4j
        restart: always
        environment: 
            NEO4J_AUTH : neo4j/test