version: '3'
services:
  envoy:
    image: envoyproxy/envoy:v1.17-latest
    container_name: envoy
    ports:
        # - "10000:10000"
        - "8080:8080"
    volumes:
        - ./envoy.yaml:/etc/envoy/envoy.yaml
#     networks:
#         - default
    
# networks:
#     default:
#         name: sol-docker