global:
  scrape_interval: 30s
  scrape_timeout: 10s
  external_labels:
    monitor: 'Monitoring'

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'idonotexists:564'
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['prometheus:9090']
  - job_name: 'win-exporter'
    static_configs: 
      - targets: ['host.docker.internal:9182']
  - job_name: 'cAdvisor' 
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'nginx' 
    metrics_path: /metrics
    static_configs:
      - targets: ['nginx-exporter:9113']
  - job_name: 'node'
    metrics_path: /metrics
    static_configs:
      - targets: ['node-exporter:9100']  

# global:
#   scrape_interval: 5s
#   external_labels:
#     monitor: 'Monitoring'
# scrape_configs:
#   - job_name: 'prometheus' 
#     static_configs: 
#       - targets: ['192.168.1.229:9090']
#   - job_name: 'node-exporter' 
#     static_configs: 
#       - targets: ['192.168.1.229:9100']
#   - job_name: 'cAdvisor' 
#     static_configs:
#       - targets: ['192.168.1.229:8080']
