version: '3.3'
services:
    jenkins:
        ports:
            - '8080:8080'
            - '50000:50000'
        volumes:
            - 'jenkins_home:/var/jenkins_home'
        image: 'jenkins/jenkins:lts-jdk11'
        container_name: 'jenkins'