# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:

  kafka-0:
    image: docker.io/bitnami/kafka:3.9
    container_name: kafka-0
    ports:
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=INSIDE://kafka-0:9092,CONTROLLER://:9093,OUTSIDE://localhost:9094
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=INSIDE://kafka-0:9092,OUTSIDE://localhost:9094
      - KAFKA_LISTENERS=INSIDE://kafka-0:9092,CONTROLLER://:9093,OUTSIDE://0.0.0.0:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,CONTROLLER:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INSIDE

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - 9100:9000
    environment:
      - KAFKA_BROKERCONNECT=kafka-0:9092
      - JVM_OPTS=-Xms32M -Xmx64M
    depends_on:
      - kafka-0

volumes:
  kafka_data:
    driver: local